# Generated by Django 5.1.6 on 2025-02-17 10:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('impressions_limit', models.IntegerField()),
                ('clicks_limit', models.IntegerField()),
                ('cost_per_impression', models.FloatField()),
                ('cost_per_click', models.FloatField()),
                ('ad_title', models.CharField(max_length=255)),
                ('ad_text', models.TextField()),
                ('start_date', models.IntegerField()),
                ('end_date', models.IntegerField()),
                ('targeting_gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('ALL', 'All')], max_length=6, null=True)),
                ('targeting_age_from', models.IntegerField(blank=True, null=True)),
                ('targeting_age_to', models.IntegerField(blank=True, null=True)),
                ('targeting_location', models.CharField(blank=True, max_length=255, null=True)),
                ('impressions_count', models.IntegerField(default=0)),
                ('clicks_count', models.IntegerField(default=0)),
                ('spent_impressions', models.FloatField(default=0.0)),
                ('spent_clicks', models.FloatField(default=0.0)),
                ('spent_total', models.FloatField(default=0.0)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='advertisers.advertiser')),
            ],
        ),
    ]
