# Generated by Django 5.1.6 on 2025-02-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0002_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='spent_total',
        ),
    ]
