# Generated by Django 5.1.6 on 2025-02-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0003_remove_campaign_spent_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='clicks_count',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='impressions_count',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='spent_clicks',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='spent_impressions',
        ),
    ]
