# Generated by Django 5.1.6 on 2025-02-20 10:34

import advertisers.models
import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0004_remove_campaign_clicks_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='adspresso-campaigns'), upload_to=advertisers.models.campaign_image_upload_to),
        ),
    ]
