# Generated by Django 5.1.6 on 2025-02-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='clicks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='impressions_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
