# Generated by Django 5.1.6 on 2025-02-19 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisers', '0003_remove_campaign_spent_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTotalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions_count', models.IntegerField(default=0)),
                ('clicks_count', models.IntegerField(default=0)),
                ('spent_impressions', models.FloatField(default=0.0)),
                ('spent_clicks', models.FloatField(default=0.0)),
                ('spent_total', models.FloatField(default=0.0)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total_stats', to='advertisers.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('impressions_count', models.IntegerField(default=0)),
                ('clicks_count', models.IntegerField(default=0)),
                ('spent_impressions', models.FloatField(default=0.0)),
                ('spent_clicks', models.FloatField(default=0.0)),
                ('spent_total', models.FloatField(default=0.0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='advertisers.campaign')),
            ],
            options={
                'unique_together': {('campaign', 'date')},
            },
        ),
    ]
