# Generated by Django 5.1.6 on 2025-02-16 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisers', '0001_initial'),
        ('clients', '0002_alter_client_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_score', to='advertisers.advertiser')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_score', to='clients.client')),
            ],
        ),
    ]
