# Generated by Django 5.1.6 on 2025-02-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MLScorer', '0001_initial'),
        ('advertisers', '0005_campaign_image'),
        ('clients', '0003_client_clicks_count_client_impressions_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mlscore',
            unique_together={('advertiser', 'client', 'score')},
        ),
    ]
